--- 
after_success: 
  - "julia -e 'cd(Pkg.dir(\"ProbabilityBoundsAnalysis.jl\")); Pkg.add(\"Coverage\"); using Coverage; Codecov.submit(Codecov.process_folder())'"
codecov: true
julia: 
  - nightly
  - 1.4
language: julia
os: 
  - linux
