--- 
after_success: 
  - "julia -e 'import Pkg; Pkg.add(\"Coverage\"); using Coverage; Coveralls.submit(Coveralls.process_folder())'"
before_install: 
  - "julia -e 'ENV[\"PYTHON\"]=\"\"; using Pkg; Pkg.add(\"Conda\"); using Conda; Conda.add(\"matplotlib\"); Pkg.add(\"PyCall\"); Pkg.build(\"PyCall\"); Pkg.add(\"PyPlot\");'"
codecov: true
julia: 
  - nightly
  - 1.4
language: julia
os: 
  - linux
