name = "ProbabilityBoundsAnalysis"
uuid = "cd73f0b2-6f06-11ea-242f-83a09de6a7cf"
authors = ["Ander Gray <ander.gray@liverpool.ac.uk>"]
version = "0.1.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
IntervalArithmetic = "d1acc4aa-44c8-5952-acd4-ba5d80a2a253"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"

[compat]
Distributions = "0.23.1"
Interpolations = "0.12.8"
IntervalArithmetic = "0.15.2, 0.16"
Plots = "0.29.8, 1.0"
PyCall = "1.91.4"
julia = "1.0.3"
